/**
 * Dictionary of route name constants to their human readable names.
 */
enum Routes {
  HOME = 'HOME',
  LOGIN = 'LOGIN',
  REGISTER = 'REGISTER',
  SHOP = 'SHOP',
  MENU = 'MENU',
  SECTIONS = 'SECTIONS',
  PRODUCT_LIST = 'PRODUCT_LIST',
  PRODUCT = 'PRODUCT',
  SUB_SECTIONS = 'SUB_SECTIONS',
  CART = 'CART',
  CHECKOUT = 'CHECKOUT',
  PAYMENT = 'PAYMENT',
  SHIPPING = 'SHIPPING',
  PAYMENT_SELECTION = 'PAYMENT_SELECTION',
  PROFILE = 'PROFILE',
  CHANGE_PASSWORD = 'CHANGE_PASSWORD',
  CHANGE_EMAIL = 'CHANGE_EMAIL',
  SHIPPING_ADDRESSES = 'SHIPPING_ADDRESSES',
  NEW_ADDRESS = 'NEW_ADDRESS',
  EDIT_ADDRESS = 'EDIT_ADDRESS',
  HELP = 'HELP',
  HELP_INFO = 'HELP_INFO',
  SETTINGS = 'SETTINGS',
  CONTACT_US = 'CONTACT_US',
  ORDER_HISTORY = 'ORDER_HISTORY',
  CHANGE_ADDRESS = 'CHANGE_ADDRESS'
}

export default Routes;
